# Conclusion

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

With this report, we tried to find out if there were any links between European countries' wealth, their diabetes rates and their food consumption. Our end goal was to find out if there was a typical diet that was attributed to a certain GDP level and who therefore affected the population's diabetes, in order to provide an example for governments for when they have to make decisions on food supply while considering public health. Even though we tried using multiple methods and metrics like the correlation coefficient, trying to fit linear models and cluster analysis to answer our research questions, we couldn't exactly find a lot of meaningful and strong relationships between our various variables.

Our control question on the negative correlation between a country's GDP and its diabetes prevalence was confirmed with our data without outliers. The general analysis was enough to answer our questions and going deeper within clusters didn't help us find better results.

Moreover, a hypothesis that we had was that since the GDP and the diabetes rate of a country are negatively correlated, a country with a higher GDP would consume less calories. To our surprise, our data showed the opposite, but then again we didn't have significant results. Though, this result could make sense when we consider that a higher GDP means access to more resources like food and therefore the consumption of the population is higher.

As for the relationship between the GDP and the consumption of macronutrients, we found out that richer countries in Europe tend to consume more protein sourced from animals and fats (like beef, salmon, avocados etc which tend to be more expensive), whereas poorer countries consume more protein sourced from plants and carbohydrates (like lentils, potatoes and beans which are cheaper).

Then we checked the relationship between the diabetes prevalence in a country and the consumption of different macronutrients. Once again contrary to our hypothesis, it seems from our results that a higher consumption of animal protein could be related to a lower rate of diabetes, which would be counter-intuitive to M. Adeva-Andany's (2019) article "Dietary habits contribute to define the risk of type 2 diabetes in humans". The consumption of fat was also negatively correlated to diabetes prevalence, whereas it was the opposite for the consumption of plant protein and carbs. This last one makes more sense to us. However, the effect of all macronutrients except protein on diabetes were highly significant for women, therefore we make the assumption that malnutrition has a greater impact on the diabetes in women than in men.

High GDP countries consume more fat and animal protein, but have a lower diabetes rate in Europe and our results suggest that consuming more fat does not equal higher diabetes. One hypothesis we have found to explain this phenomenon may be that richer countries do more diabetes prevention and have better hospital infrastructure and medical care. Another hypothesis is that the rate of diabetes is more related to the level of exercise in a country. 

### Limitations

The results of the analysis within clusters often didn't make sense or were not significant/strong enough. We didn't have too many countries to work with but maybe we could have tried to increase the cluster number to decrease variance within clusters. Then however we would have the risk of having even smaller samples and less observations which are not good for statistical accuracy.

Another limitation is that the linear regressions were not always significant and it was complicated to find the right relationship between the different variables if there were any. Nutrition and health is often complex and it is logical that a simple linear regression with one variable is not enough to explain another.


### To go further 

To go further, it would be interesting to take into account other countries outside of Europe which are more varied, in order to make more distinct clusters. It would have been interesting to know more about the United States, for example, a country with a high GDP and a high rate of diabetes.

Another interesting thing would be to calculate a ratio of the consumption of carbs to fat and see if this index could give us more explanations on the diabetes prevalence in different countries.