# Exploratory data analysis

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R")) #we should also add the data.Rmd file no ?
```

* Mapping out the underlying structure
* Identifying the most important variables
* Univariate visualizations
* Multivariate visualizations
* Summary tables



## GDP per country

```{r}
ggplot(data = GDP_diabetes_cal) +
  geom_point(mapping = aes(x = country_code, y = avg_gdp))
```


## Plotting GDP against Diabetes (Men & Women)
```{r}
plot(GDP_diabetes_cal$avg_gdp, GDP_diabetes_cal$prop_men_diabetes)
plot(GDP_diabetes_cal$avg_gdp, GDP_diabetes_cal$prop_women_diabetes)
```


#GDP againt total calories, each macronut Clara

```{r}
#Plotting different cal consumption with GDP (trying to find a trend)
plot(GDP_diabetes_cal$avg_gdp, GDP_diabetes_cal$total_consumption,
main="Caloric consumption by country",
ylab="",
type="p",
col="blue")
lines(GDP_diabetes_cal$avg_gdp,GDP_diabetes_cal$cal_fat, col="red", type="p")
lines(GDP_diabetes_cal$avg_gdp,GDP_diabetes_cal$cal_carbs, col="green", type="p")
lines(GDP_diabetes_cal$avg_gdp,GDP_diabetes_cal$cal_prot_animal, col="orange", type="p")
lines(GDP_diabetes_cal$avg_gdp,GDP_diabetes_cal$cal_prot_plant, col="purple", type="p")
legend("topleft", c("Total Tonsumption","Fat", "Carbs", "Animal Protein", "Plant Protein"),
fill=c("blue","red", "green", "orange", "purple"))

#ggplot total consumption against GDP
ggplot(GDP_diabetes_cal, aes(x=GDP_diabetes_cal$avg_gdp, y=GDP_diabetes_cal$total_consumption)) +
  geom_point() + # Show dots
  geom_text(
    label= (GDP_diabetes_cal$country_code),  
    nudge_x = 0.25, nudge_y = 0.25, 
    check_overlap = T)

#ggplot total consumption against Diabetes
ggplot(GDP_diabetes_cal, aes(x=GDP_diabetes_cal$prop_men_diabetes, y=GDP_diabetes_cal$total_consumption)) +
  geom_point() + # Show dots
  geom_text(
    label= (GDP_diabetes_cal$country_code),  
    nudge_x = 0.25, nudge_y = 0.25, 
    check_overlap = T)
##the last 2 plots not the same distributions!! so Question 1 not so trivial after all

ggplot(data = GDP_diabetes_cal, mapping = aes(x = country_code, y = total_consumption, color = as.factor("country_name"))) + geom_point()

#ranking GDP and total consumption 
GDP_diabetes_cal$rank_GDP <- rank(GDP_diabetes_cal$avg_gdp)
GDP_diabetes_cal$rank_Consumption <- rank(GDP_diabetes_cal$total_consumption)


#Rank btw them 
GDP_diabetes_cal <-within(GDP_diabetes_cal, rank3 <- rank(order(rank_GDP, rank_Consumption), ties.method='first'))
  order_by(rank3)
#not the same so ranking maybe link btw regimes and lowest diabetes rates??
  
```






#Diabetes againt calories Fabien

```{r}
plot(GDP_diabetes_cal$cal_carbs,GDP_diabetes_cal$prop_men_diabetes)
plot(GDP_diabetes_cal$total_consumption,GDP_diabetes_cal$prop_women_diabetes)
ggplot(data = GDP_diabetes_cal) +
  geom_smooth(mapping = aes(x = total_consumption, y = prop_men_diabetes))
```


```{r echo= FALSE}
plot(GDP_diabetes_cal$avg_gdp, GDP_diabetes_cal$total_consumption)
```



