# Introduction

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

## Overview and Motivation

During the last 2 years, COVID-19 has been a main focus of the news. Though around 3% of the world population had COVID-19, diabetes can be considered as an even bigger health problem. Indeed, according to the International Diabetes Foundations (IDF), in 2019, 463 million adults were living with diabetes (around 6-7% of the world population) and this number is forecasted to rise to 700 million by 2050. Furthermore, 90% of cases of diabetes are of type 2, which means it results mainly from bad habits and not genetics. However both types of diabetes can be treated and/or prevented with a healthier diet and more physical activity. Additionally, according to the WHO, low income countries are more susceptible to having higher diabetes prevalence. Living in Europe, we observed that diabetes rates differ a lot from one country to another, so we wanted to find out if these rates were indeed linked to a country’s income, and if the nutritious composition of richer states’ population’s diet is also affected by this income difference and if yes, how it is affected. 

## Related Work

The article published by M. Adeva-Andany (2019) “Dietary habits contribute to define the risk of type 2 diabetes in humans” states that type 2 diabetes could be prevented by a better  dietary habits.They also found that higher animal protein consumption induced a greater risk of developing type 2 diabetes regardless of body mass index. In addition, they have also said that: "Low intake of animal products is linked to high educational level so that well-informed individuals tend to consume diets with elevated content of vegetable food" which can be linked to the GDP. (https://www.sciencedirect.com/science/article/pii/S240545771930419X?casa_token=Dzx3S9e8WgsAAAAA:IUYCy_uePTCOLUn38QUDO5KtpJopGpHdNIXZtHVVsGy9NWuXQ78Hp2juTvtjFQp67Dk2by-fMgPfrg) 
  

## Research questions

Therefore, we would like to find out answers to the following questions :

  1. Do European countries that have higher GDPs really have lower diabetes prevalence ?

  2. Do European countries that have higher GDPs consume less calories ?

  3. How do the proportions of macronutrients (animal protein/plant protein/fat/carbohydrates) consumed differ between richer and poorer governments ?

  4. And how do these differences relate to the diabetes prevalence in these countries ?

  5. What is the typical diet that can be observed in richer states that relates to lower diabetes prevalence ?